### ISSUE TITLE
MasterKey4 Revision reads "Unknown" for NSPs but "5.0.0+" for XCIs

### ISSUE THREAD

**Issue by Stone-D** [StudentBlake/XCI-Explorer#23]
NSP (_Titan Quest [UPD][0100605008268800][v65536][mk4].nsp_):
`MasterKey4 (Unknown)`

XCI (_0297 - Dead Cells (Europe) (En,Ja,Fr)[mk4].xci_):
`MasterKey4 (5.0.0+)`

All lower MasterKeys show the OS version as expected.

**Comment by garoxas** [comment]
update your hactool to v1.2.0 https://github.com/SciresM/hactool/tree/1.2.0

this is external issue
pre1.2.0 hactool does not know the correct firmware version for masterkey 4 or above and will resort to use *Unknown*
and this should happen again later in the future when games with masterkey 5 (6.0.0) is out since the latest version of hactool still not handle it

**Comment by garoxas** [comment]
I made a PR #25 if you're interested to handle this internally
